### ISSUE TITLE
Windows DLL issues on import: vs2010_runtime dependency missing in conda package. 

### ISSUE THREAD

**Issue by piotr-teterwak** [spacy-io/spaCy#353]
When I install spaCy in a clean conda environment(Windows 8.1), everything seems to install properly. However, when I try to import in an iPython session, it chokes on DLL imports. When I install `vs2010_runtime`, though, everything works 

I'm using Miniconda. Here's my output of `conda info --all`

```
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\dato\Desktop\spacy_testing\Miniconda  (writable)
  default environment : C:\Users\dato\Desktop\spacy_testing\Miniconda
     envs directories : C:\Users\dato\Desktop\spacy_testing\Miniconda\envs
        package cache : C:\Users\dato\Desktop\spacy_testing\Miniconda\pkgs
         channel URLs : https://conda.anaconda.org/spacy/win-64/
                        https://conda.anaconda.org/spacy/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\dato\.condarc
    is foreign system : False

# conda environments:
#
root                  *  C:\Users\dato\Desktop\spacy_testing\Miniconda

sys.version: 2.7.11 |Continuum Analytics, Inc.| (defa...
sys.prefix: C:\Users\dato\Desktop\spacy_testing\Miniconda
sys.executable: C:\Users\dato\Desktop\spacy_testing\Miniconda\python.exe
conda location: C:\Users\dato\Desktop\spacy_testing\Miniconda\lib\site-packages\conda
conda-build: None
conda-env: C:\Users\dato\Desktop\spacy_testing\Miniconda\Scripts\conda-env.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\dato\Desktop\spacy_testing\Miniconda\Library\bin;C:\Users\dato\AppData\Local\GitHub\PortableGit_c7e0cbde9
2ba565cb218a521411d0e854079a28c\cmd;C:\Users\dato\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a
28c\usr\bin;C:\Users\dato\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\usr\share\git-tfs;C:
\Users\dato\AppData\Local\Apps\2.0\W84WLROD.B0E\NW74TWMM.MNZ\gith..tion_317444273a93ac29_0003.0000_328216539257acd4;C:\U
sers\dato\AppData\Local\GitHub\lfs-amd64_1.1.0;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\ProgramData\Oracle\Java\
javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Git\cmd;C:\msys64;c:\msys64\usr\bin;C:\Program Files\nodejs\;C:\Users\dato\Desktop\spacy_testing\Miniconda;C:\User
s\dato\Desktop\spacy_testing\Miniconda\Scripts;C:\Users\dato\Desktop\spacy_testing\Miniconda\Library\bin;C:\Users\dato\M
iniconda2;C:\Users\dato\Miniconda2\Scripts;C:\Users\dato\Miniconda2\Library\bin;C:\jenkins\workspace\Launcher-Scenario-T
est\label\erdos-win81\scenario_test\tests\anaconda6;C:\jenkins\workspace\Launcher-Scenario-Test\label\erdos-win81\scenar
io_test\tests\anaconda6\Scripts;C:\jenkins\workspace\Launcher-Scenario-Test\label\erdos-win81\scenario_test\tests\anacon
da6\Library\bin;C:\Users\dato\Anaconda2;C:\Users\dato\Anaconda2\Scripts;C:\jenkins\workspace\smoke-tests-release-multi\l
abel\erdos-win81\miniconda-smoke-test;C:\jenkins\workspace\smoke-tests-release-multi\label\erdos-win81\miniconda-smoke-t
est\Scripts;C:\jenkins\workspace\smoke-tests-release-multi\label\erdos-win81\miniconda-smoke-test\Library\bin;C:\jenkins
\workspace\smoke-tests-release-multi\label\erdos-win81miniconda-smoke-test;C:\jenkins\workspace\smoke-tests-release-mult
i\label\erdos-win81miniconda-smoke-test\Scripts;C:\jenkins\workspace\smoke-tests-release-multi\label\erdos-win81minicond
a-smoke-test\Library\bin;C:\jenkins\workspace\Scenario-Tests\label\erdos-win81\tests\anaconda6;C:\jenkins\workspace\Scen
ario-Tests\label\erdos-win81\tests\anaconda6\Scripts;C:\jenkins\workspace\Scenario-Tests\label\erdos-win81\tests\anacond
a6\Library\bin;C:\Python27;C:\Users\dato\AppData\Roaming\npm
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    C:\Users\dato\.continuum
    C:\Users\dato\AppData\Roaming\Continuum
    C:\Users\dato\Desktop\spacy_testing\Miniconda\licenses
License files (license*.txt):
Package/feature end dates:
```

Here's what happens when I import spaCy:

```

In [1]: import spacy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c080f6458562> in <module>()
----> 1 import spacy

C:\Users\dato\Desktop\spacy_testing\Miniconda\lib\site-packages\spacy\__init__.py in <module>()
----> 1 from . import util
      2 from .en import English
      3
      4
      5 def load(name, vectors=None, via=None):

C:\Users\dato\Desktop\spacy_testing\Miniconda\lib\site-packages\spacy\util.py in <module>()
     12
     13 from . import about
---> 14 from .attrs import TAG, HEAD, DEP, ENT_IOB, ENT_TYPE
     15
     16

ImportError: DLL load failed: The specified module could not be found.
```

One interesting note is that when I install `conda install vs2010_runtime`, everything works. I think that there is missing dependency in the conda package for windows. Also,I think its common for there to be system libraries installed that provide these required DLL's, so the issue may not be that common.

**Comment by henningpeters** [comment]
I had assumed that conda comes with the VC++ runtime libraries installed by default. At least when I create a new conda environment on my system it installs it by default:

```
> conda list
# packages in environment at C:\Users\conda\Miniconda3\envs\x:
#
pip                       8.1.1                    py35_1
python                    3.5.1                         4
setuptools                20.7.0                   py35_0
vs2015_runtime            14.00.23026.0                 0
wheel                     0.29.0                   py35_0
```

There is not much info on how to package this properly. By looking at some recipes at https://github.com/ContinuumIO/anaconda-recipes it seems they are typically using the meta.yml features flag. I will give it a try, otherwise please feel free to make any suggestions. Here's the latest meta.yml:

```
about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength NLP
package:
  name: spacy
  version: 0.100.6
requirements:
  build:
  - python
  - setuptools
  - numpy
  - murmurhash >=0.26,<0.27
  - cymem >=1.30,<1.32.0
  - preshed >=0.46.1,<0.47
  - thinc >=5.0.0,<5.1.0
  - plac
  - six
  - ujson
  - cloudpickle
  - sputnik >=0.9.2,<0.10.0
  run:
  - python
  - numpy
  - murmurhash >=0.26,<0.27
  - cymem >=1.30,<1.32.0
  - preshed >=0.46.1,<0.47
  - thinc >=5.0.0,<5.1.0
  - plac
  - six
  - ujson
  - cloudpickle
  - sputnik >=0.9.2,<0.10.0
source:
  fn: spacy-0.100.6.tar.gz
  md5: 890ff5a1855511b38084838bbbd2bcd1
  url: https://pypi.python.org/packages/27/fe/1518aab67840fcec4303ad5a36e7baebc42d7df5775f75f50b3d53ecabcd/spacy-0.100.6.tar.gz
test:
  imports:
  - spacy
```
